version: "2.15.1"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  suppliers-data-service:
    build:
      dockerfile: Dockerfile
      context: ./suppliers-data-service
    depends_on:
      - events
      - queries
    environment:
      SUPPLIERS_DATA_SERVICE_PORT: 3007
      POSTGRES_EVENTS_PORT: 5433
      POSTGRES_QUERIES_PORT: 5434
      POSTGRES_HOST: host.docker.internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      SUPPLIERS_DATA_SERVICE_LOGIN: DATAservLogin
      SUPPLIERS_DATA_SERVICE_PASSWORD: DATAservpassword
      BROKER_URL: localhost:29092
      KAFKA_CONSUMER_GROUP_ID: 1
      KAFKA_CLIENT_ID: 1
    ports:
      - "3007:3007"

  suppliers-management-app:
    build:
      dockerfile: Dockerfile
      context: ./supplier-management-app
    environment:
      SUPPLIER_MANAGEMENT_APP_PORT: 3100
      SUPPLIER_SERVICE_URL: host.docker.internal:50051
    ports:
      - "3100:3100"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  events:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: events

  queries:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: queries

